import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/Index.module.scss'
import Navbar from '@/Components/Navbar/Navbar'
import HomePage from '@/Components/Home/HomePage'
import Features from '@/Components/Home/FeaturesOverview'
import { useSelector } from 'react-redux'
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })
export default function Home() {  
  return (
    <>
      <Head>
        <title>Home | Create Meeting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo.avif" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;500;700;800&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;500;700;800&family=Roboto:wght@200;300;400;500&display=swap" rel="stylesheet"></link>0
        <link href="https://fonts.googleapis.com/css2?family=Playfair:wght@400;500&display=swap" rel="stylesheet"/>
      </Head>
      <main  className={styles.Main}>
          <Navbar/>
          <HomePage/>
          <Features/>
          <Link href={"/chatbox"}>Home page</Link>
      </main>
    </>
  )
}
